config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  #To do custom routes on resourced routes, use except then configure under
  #except expects an array
  resources :portfolios, except: [:show] 
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio-singular'
  get 'portfolios/angular-items', to: 'portfolios#angular'

  #get 'pages/about' | Below is how you map without pages/about
  get 'about-me', to: 'pages#about' #controller on the left side, action on the right side of hash
  #get 'pages/contact'
  get 'contact', to: 'pages#contact' #'contact' could be name ANYTHING. so long as pages#contact is intact

  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #sets root to home. Basically changing your homepage to home
  root to: 'pages#home'

  #Custom route for blogs/:id/toggle_status
  resources :blogs do
    member do
      get :toggle_status
    end
  end


end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies

  #So you can pull in technology attributes and reject if no technologies
  #You can build with this kind of code with an array of technology items
  # => Portfolio.create!(title: "Web App", subtitle: "asdasd", body: "asdjnkjng", technologies_attributes: [{name: "Ruby"}, 
  #     {name: "Rails"}, {name: "Angular"}, {name: "Ionic"}])
  accepts_nested_attributes_for :technologies, 
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  include Placeholder

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body, :mainImage, :thumbImage

  #Custom Query accessible via Portfolio.angular
  def self.angular
    where(subtitle: 'Angular 2')
  end

  #Essentially the same thing as above, but using scope keyword
  #scope :angular_portfolio_items, -> { where(subtitle: 'Angular 2') }

  after_initialize :set_defaults

  def set_defaults
    # '||=' is essentially an if nil then set to ... statement
    self.mainImage ||= Placeholder.imageGenerator(height: '700', width: '400')
    self.thumbImage ||= Placeholder.imageGenerator(height: '350', width: '200')
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController

  def index #generally where a whole list is displayed
    @portfolioItems = Portfolio.all 
    #This is a call to the Portfolio MODEL from this CONTROLLER and assigning 
    # the values of all Portfolio items to @portfolio_items which can be accessed by the view
    #In order to make use of @portfolio_items a file in views must be made for portfolios index 'index.html.erb'
  end

  def angular
    @portfolioItemsAngular = Portfolio.angular
  end


  def new
    @portfolioItem = Portfolio.new 
    #Hardcoded 3 technologies will be built for the instantiated Portfolio
    3.times { @portfolioItem.technologies.build }
  end


  def create
    @portfolioItem = Portfolio.new(params.require(:portfolio).permit(:title, :subtitle, :body, technologies_attributes: [:name]))

    respond_to do |format|
      if @portfolioItem.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end


  def edit
    @portfolioItem = Portfolio.friendly.find(params[:id])
  end


  def show
    @portfolioItem = Portfolio.friendly.find(params[:id])
  end


  def update
    @portfolioItem = Portfolio.friendly.find(params[:id])

    respond_to do |format|
      if @portfolioItem.update(params.require(:portfolio).permit(:title, :subtitle, :body))
        format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    #The lookup
    @portfolioItem = Portfolio.friendly.find(params[:id])

    #This will destroy the record
    @portfolioItem.destroy

    #The redirect after destroying
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio record was removed.' }
    end
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path %>

<% @portfolioItemsAngular.each do |item| %> 
  <h3><%= link_to item.title, portfolio_singular_path(item) %></h3> 
  <p><%= item.subtitle %></p> 
  <p><%= item.body %></p>
  <%= image_tag item.thumbImage unless item.thumbImage.nil? %>
  <p><%= link_to "Edit", edit_portfolio_path(item) %>
  <%= link_to "Delete Portfolio Item", portfolio_path(item), method: :delete, data: { confirm: "Are you sure?" } %></p>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit Portfolio Item</h1>

<%= form_for(@portfolioItem) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path %>

<% @portfolioItems.each do |item| %> 
  <h3><%= link_to item.title, portfolio_singular_path(item) %></h3> 
  <p><%= item.subtitle %></p> 
  <p><%= item.body %></p>
  <%= image_tag item.thumbImage unless item.thumbImage.nil? %>
  <p><%= link_to "Edit", edit_portfolio_path(item) %>
  <%= link_to "Delete Portfolio Item", portfolio_path(item), method: :delete, data: { confirm: "Are you sure?" } %></p>
<% end %>

app/views/portfolios/new.html.erb
<h1>Create a New Portfolio Item</h1>

<%= form_for(@portfolioItem) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |technologyForm| %>
      <li>
        <%= technologyForm.label :name %>
        <%= technologyForm.text_field :name %>
      </li>
    <% end %>
  </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolioItem.mainImage unless @portfolioItem.mainImage.nil? %>

<h1><%= @portfolioItem.title %></h1> 

<em><%= @portfolioItem.subtitle %></em>

<p><%= @portfolioItem.body %></p>

<h2>Technologies Used:</h2>

<% @portfolioItem.technologies.each do |technology| %>
  <p><%= technology.name %></p>
<% end %>

<%= link_to "Edit", edit_portfolio_path(@portfolioItem.id) %>
<%= link_to "Back", portfolios_path %>